matrix:
- name: Markdown
  aspell:
    d: en_US
    ignore-case: true
    lang: en
  default_encoding: utf-8
  dictionary:
    encoding: utf-8
    wordlists:
    - .github/.wordlist.txt
  hunspell:
    d: en_US
    ignore-case: true
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources: ['_drafts/**/*.md', '_posts/**/*.md']
