version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - ci
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "-"
    schedule:
      day: monday
      interval: weekly
      time: "16:00"
    versioning-strategy: auto
