version: 2
updates:
  - package-ecosystem: bundler
    allow:
      - dependency-type: "all"
    directory: "/"
    ignore:
      - dependency-name: "jekyll-sass-converter"
    labels:
      - dependencies
      - ruby
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "-"
    schedule:
      day: monday
      interval: monthly
      time: "10:00"
    versioning-strategy: auto

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - ci
      - dependencies
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "-"
    schedule:
      day: monday
      interval: weekly
      time: "10:00"
    versioning-strategy: auto
