# Site settings
baseurl: '/blog'
theme: jekyll-theme-slate
url: https://torrocus.com

description: >
  Full-stack developer, who loves challenges, tries to write a tech blog about
  Ruby on Rails, design patterns and application architecture.
lang: en
title: Less is more

google_analytics: 'UA-62202006-13'
