# Site settings
baseurl: '/blog'
url: &url https://torrocus.com

# Meta settings
author: torrocus
description: >
  Full-stack developer, who loves challenges, tries to write a tech blog about
  Ruby on Rails, design patterns and application architecture.
lang: en
title: Less is more

# Theme settings
theme: minima

google_analytics: 'UA-127739651-1'
highlighter: rouge
show_excerpts: true

disqus:
  shortname: torrocus

# header_pages:

minima:
  date_format: '%Y-%m-%d'

plugins:
  - jekyll-sitemap
  - jekyll-time-to-read

twitter:
  card: summary
  username: torrocus
