# Site settings
baseurl: '/blog'
theme: minima
url: https://torrocus.com

author: torrocus
description: >
  Full-stack developer, who loves challenges, tries to write a tech blog about
  Ruby on Rails, design patterns and application architecture.
lang: en
title: Less is more

google_analytics: 'UA-62202006-13'
highlighter: rouge
show_excerpts: true

disqus:
  shortname: torrocus

# header_pages:

gems:
  - jekyll-last-modified-at

twitter:
  card: summary
  username: torrocus
