# Site settings
baseurl: '/blog'
url: &url https://torrocus.com

# Meta settings
author: torrocus
description: >
  Full-stack developer, who loves challenges, tries to write a tech blog about
  Ruby on Rails, design patterns and application architecture.
lang: en
title: Less is more

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md

permalink: /:title/
feed:
  excerpt_only: true

google_analytics: 'UA-127739651-1'
highlighter: rouge
show_excerpts: true

compress_html:
  blanklines: false
  clippings: all
  comments: all
  ignore:
    envs: development
  # endings: all
  # profile: true
  # startings: all

disqus:
  shortname: torrocus

# header_pages:

minima:
  date_format: ' '

sass:
  style: compressed

twitter:
  card: summary
  username: torrocus
