name: Misspell checker
on:
  pull_request:
    types: [opened, synchronize]
    paths: ['_drafts/**', '_posts/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  misspell:
    name: Misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Check misspell
        uses: reviewdog/action-misspell@v1
        with:
          fail_on_error: true
          filter_mode: diff_context
          level: error
          locale: US
          pattern: "*.md"
          reporter: github-pr-check
