name: Spelling action
on:
  pull_request:
    types: [opened, synchronize]
    paths: ['_drafts/**', '_posts/**']
  push:
    paths: ['_drafts/**', '_posts/**']
  workflow_dispatch:
    inputs:
      spellchecker:
        default: aspell
        description: The tool to spell check
        options: ['aspell']
        required: true
        type: choice

jobs:
  spelling:
    env:
      SPELLCHECKER_FALLBACK: aspell
    name: Spelling job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Update pip
        run: python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: python -m pip install pyspelling
      - name: Install aspell
        run: sudo apt-get install aspell aspell-en
      - name: Spell check
        run: python -m pyspelling -c ${{ env.CONFIG }} -s ${{ env.SPELLCHECKER }}
        env:
          CONFIG: '.github/.spellcheck.yml'
          SPELLCHECKER: ${{ github.event.inputs.spellchecker || env.SPELLCHECKER_FALLBACK }}
