name: Spelling checker
on:
  workflow_call:
    inputs:
      config:
        description: Config file
        required: true
        type: string
      spellchecker:
        description: Spellchecker (aspell / hunspell)
        required: true
        type: string

jobs:
  spelling_checker:
    name: Spelling checker
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Update pip
        run: python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: python -m pip install pyspelling
      - name: Install aspell
        run: sudo apt-get install aspell aspell-en aspell-pl
      - name: Spell check
        run: python -m pyspelling -c ${{ inputs.config }} -s ${{ inputs.spellchecker }}
